trailing_comma = nothing
join_lines_based_on_source = true
always_for_in = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
pipe_to_function_call = false
short_to_long_function_def = false
always_use_return = false
whitespace_in_kwargs = false
separate_kwargs_with_semicolon = true
align_struct_field = true
align_conditional = true
align_assignment = true
align_pair_arrow = true
align_matrix = true